alias bd="base64 --decode"
alias cdnv="cd ~/.config/nvim/"
alias cdr="cd \$(git rev-parse --show-toplevel)"
alias cls="clear"
alias diff="diff -W \$COLUMNS -y --suppress-common-lines"
alias fl="git grep --line-number . |fzf --delimiter : --nth 3.. --bind 'enter:become(nvim {1} +{2})'"
alias g="git"
alias gchm="git checkout master"
alias gd="git diff"
alias gdf="git diff --name-status -B -M -C"
alias gdm="git diff master"
alias gdt="git difftool --no-prompt --tool=nvimdiff"
alias gp="git fetch && git pull -q; git push"
alias gra="git restore ./ && git clean -f"
alias gs="git status"
alias kge="k get events --sort-by=.metadata.creationTimestamp"
alias kgy="k get -o yaml"
alias l="ls -la"
alias ll="ls -la"
alias nvimdiff='nvim -d'
alias ob="cd ~/git/obsidian/ && nvim -c 'Obsidian today' && cd -"
alias ossl="openssl x509 -noout -text"
alias rb="git pull --rebase origin"
alias srr="ssh -t -oStrictHostKeyChecking=no -q -A -K -l root"
alias vimdiff='nvim -d'
